### Users Create (signup)(WORKING)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Kate",
  "email": "kate@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create (login)(WORKING)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "camden@gmail.com",
  "password": "password"
}

### Users Show(Working)
GET http://localhost:3000/users/:id
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDczNjIxMDB9.lfzx3a-vg0sWXpn8U-ca6y4ThaI3BjB9mbiomXqGIpY

### listings Create(Working)
POST http://localhost:3000/listings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDczNjIxMDB9.lfzx3a-vg0sWXpn8U-ca6y4ThaI3BjB9mbiomXqGIpY

{
  "brand": "Suzuki",
  "model": "GSXR-750",
  "year": "2005",
  "description": "the most excellent of track machines",
  "image_url": "https://www.motorcyclespecs.co.za/Gallery%20%20A/SUZUKI%20GSXR750%20%2004%20%203.jpg",
  "location": "Tempe, Arizona"  
}

### Listings Index(WORKING)
GET http://localhost:3000/listings


### Listings Show(WORKING)
GET http://localhost:3000/listings/1

### Listings Update(WORKING)
PATCH http://localhost:3000/listings/1
Content-Type: application/json

{
  "brand": "HONDA"
}

### Listings Destroy(WORKING)
DELETE http://localhost:3000/listings/1

### Conversations Index(WORKING)
GET http://localhost:3000/conversations
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDczNjIxMDB9.lfzx3a-vg0sWXpn8U-ca6y4ThaI3BjB9mbiomXqGIpY

### Conversations Create(Working)
POST http://localhost:3000/conversations
Content-Type: application/json

{
  "leaser_id": 4  
}

### Conversations Show(Working)
GET http://localhost:3000/conversations/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDczNjIxMDB9.lfzx3a-vg0sWXpn8U-ca6y4ThaI3BjB9mbiomXqGIpY

### Messages Create(Working)
POST http://localhost:3000/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDczNjIxMDB9.lfzx3a-vg0sWXpn8U-ca6y4ThaI3BjB9mbiomXqGIpY

{
  "body": "That is the coolest bike I have ever seen in my life, I NEED TO RIDE IT"
}